Controllers/Apply_Job_DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Employement_Project_MVC.Data;
using Employement_Project_MVC.Models;
using Microsoft.AspNetCore.Authorization;

namespace Employement_Project_MVC.Controllers
{
    [Authorize]
    public class Apply_Job_DetailController : Controller
    {
        private readonly Employement_Project_MVCContext _context;

        public Apply_Job_DetailController(Employement_Project_MVCContext context)
        {
            _context = context;
        }
       
        // GET: Apply_Job_Detail
        public async Task<IActionResult> Index()
        {
            var employement_Project_MVCContext = _context.Apply_Job_Detail.Include(a => a.Candidate_Detail).Include(a => a.Job_Detail);
            return View(await employement_Project_MVCContext.ToListAsync());
        }

        // GET: Apply_Job_Detail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apply_Job_Detail = await _context.Apply_Job_Detail
                .Include(a => a.Candidate_Detail)
                .Include(a => a.Job_Detail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (apply_Job_Detail == null)
            {
                return NotFound();
            }

            return View(apply_Job_Detail);
        }

        // GET: Apply_Job_Detail/Create
        public IActionResult Create()
        {
            ViewData["Candidate_DetailId"] = new SelectList(_context.Candidate_Detail, "Id", "Mobile_no_of_candidate");
            ViewData["Job_DetailId"] = new SelectList(_context.Set<Job_Detail>(), "Id", "Id");
            return View();
        }

        // POST: Apply_Job_Detail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Candidate_DetailId,Job_DetailId,Candidate_availabilities,Candidate_notice_period")] Apply_Job_Detail apply_Job_Detail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(apply_Job_Detail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Candidate_DetailId"] = new SelectList(_context.Candidate_Detail, "Id", "Mobile_no_of_candidate", apply_Job_Detail.Candidate_DetailId);
            ViewData["Job_DetailId"] = new SelectList(_context.Set<Job_Detail>(), "Id", "Id", apply_Job_Detail.Job_DetailId);
            return View(apply_Job_Detail);
        }

        // GET: Apply_Job_Detail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apply_Job_Detail = await _context.Apply_Job_Detail.FindAsync(id);
            if (apply_Job_Detail == null)
            {
                return NotFound();
            }
            ViewData["Candidate_DetailId"] = new SelectList(_context.Candidate_Detail, "Id", "Mobile_no_of_candidate", apply_Job_Detail.Candidate_DetailId);
            ViewData["Job_DetailId"] = new SelectList(_context.Set<Job_Detail>(), "Id", "Id", apply_Job_Detail.Job_DetailId);
            return View(apply_Job_Detail);
        }

        // POST: Apply_Job_Detail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Candidate_DetailId,Job_DetailId,Candidate_availabilities,Candidate_notice_period")] Apply_Job_Detail apply_Job_Detail)
        {
            if (id != apply_Job_Detail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(apply_Job_Detail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Apply_Job_DetailExists(apply_Job_Detail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Candidate_DetailId"] = new SelectList(_context.Candidate_Detail, "Id", "Mobile_no_of_candidate", apply_Job_Detail.Candidate_DetailId);
            ViewData["Job_DetailId"] = new SelectList(_context.Set<Job_Detail>(), "Id", "Id", apply_Job_Detail.Job_DetailId);
            return View(apply_Job_Detail);
        }

        // GET: Apply_Job_Detail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var apply_Job_Detail = await _context.Apply_Job_Detail
                .Include(a => a.Candidate_Detail)
                .Include(a => a.Job_Detail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (apply_Job_Detail == null)
            {
                return NotFound();
            }

            return View(apply_Job_Detail);
        }

        // POST: Apply_Job_Detail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var apply_Job_Detail = await _context.Apply_Job_Detail.FindAsync(id);
            _context.Apply_Job_Detail.Remove(apply_Job_Detail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Apply_Job_DetailExists(int id)
        {
            return _context.Apply_Job_Detail.Any(e => e.Id == id);
        }
    }
}

Controllers/Employer_DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Employement_Project_MVC.Data;
using Employement_Project_MVC.Models;
using Microsoft.AspNetCore.Authorization;

namespace Employement_Project_MVC.Controllers
{
    public class Employer_DetailController : Controller
    {
        private readonly Employement_Project_MVCContext _context;

        public Employer_DetailController(Employement_Project_MVCContext context)
        {
            _context = context;
        }

        // GET: Employer_Detail
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employer_Detail.ToListAsync());
        }

        // GET: Employer_Detail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employer_Detail = await _context.Employer_Detail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employer_Detail == null)
            {
                return NotFound();
            }

            return View(employer_Detail);
        }
        [Authorize]
        // GET: Employer_Detail/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employer_Detail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Employer_name,Date_of_establishment,Address_of_employer")] Employer_Detail employer_Detail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employer_Detail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(employer_Detail);
        }
        [Authorize]
        // GET: Employer_Detail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employer_Detail = await _context.Employer_Detail.FindAsync(id);
            if (employer_Detail == null)
            {
                return NotFound();
            }
            return View(employer_Detail);
        }

        // POST: Employer_Detail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Employer_name,Date_of_establishment,Address_of_employer")] Employer_Detail employer_Detail)
        {
            if (id != employer_Detail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employer_Detail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Employer_DetailExists(employer_Detail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employer_Detail);
        }
        [Authorize]
        // GET: Employer_Detail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employer_Detail = await _context.Employer_Detail
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employer_Detail == null)
            {
                return NotFound();
            }

            return View(employer_Detail);
        }

        // POST: Employer_Detail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var employer_Detail = await _context.Employer_Detail.FindAsync(id);
            _context.Employer_Detail.Remove(employer_Detail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Employer_DetailExists(int id)
        {
            return _context.Employer_Detail.Any(e => e.Id == id);
        }
    }
}

Controllers/Job_DetailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Employement_Project_MVC.Data;
using Employement_Project_MVC.Models;
using Microsoft.AspNetCore.Authorization;

namespace Employement_Project_MVC.Controllers
{
    public class Job_DetailController : Controller
    {
        private readonly Employement_Project_MVCContext _context;

        public Job_DetailController(Employement_Project_MVCContext context)
        {
            _context = context;
        }

        // GET: Job_Detail
        public async Task<IActionResult> Index()
        {
            var employement_Project_MVCContext = _context.Job_Detail.Include(j => j.Employer_Detail);
            return View(await employement_Project_MVCContext.ToListAsync());
        }

        // GET: Job_Detail/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job_Detail = await _context.Job_Detail
                .Include(j => j.Employer_Detail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job_Detail == null)
            {
                return NotFound();
            }

            return View(job_Detail);
        }
        [Authorize]
        // GET: Job_Detail/Create
        public IActionResult Create()
        {
            ViewData["Employer_DetailId"] = new SelectList(_context.Employer_Detail, "Id", "Id");
            return View();
        }

        // POST: Job_Detail/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Job_role,Job_type,Job_salary,Job_description,Employer_DetailId")] Job_Detail job_Detail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(job_Detail);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Employer_DetailId"] = new SelectList(_context.Employer_Detail, "Id", "Id", job_Detail.Employer_DetailId);
            return View(job_Detail);
        }
        [Authorize]
        // GET: Job_Detail/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job_Detail = await _context.Job_Detail.FindAsync(id);
            if (job_Detail == null)
            {
                return NotFound();
            }
            ViewData["Employer_DetailId"] = new SelectList(_context.Employer_Detail, "Id", "Id", job_Detail.Employer_DetailId);
            return View(job_Detail);
        }

        // POST: Job_Detail/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Job_role,Job_type,Job_salary,Job_description,Employer_DetailId")] Job_Detail job_Detail)
        {
            if (id != job_Detail.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(job_Detail);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!Job_DetailExists(job_Detail.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Employer_DetailId"] = new SelectList(_context.Employer_Detail, "Id", "Id", job_Detail.Employer_DetailId);
            return View(job_Detail);
        }
        [Authorize]
        // GET: Job_Detail/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var job_Detail = await _context.Job_Detail
                .Include(j => j.Employer_Detail)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (job_Detail == null)
            {
                return NotFound();
            }

            return View(job_Detail);
        }

        // POST: Job_Detail/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var job_Detail = await _context.Job_Detail.FindAsync(id);
            _context.Job_Detail.Remove(job_Detail);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool Job_DetailExists(int id)
        {
            return _context.Job_Detail.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employement_Project_MVC</title>
    <!--

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />-->
    <!---->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,600" />
    <link rel="stylesheet" href="css/all.min.css" />
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <link rel="stylesheet" href="slick/slick.css" />
    <link rel="stylesheet" href="slick/slick-theme.css" />
    <link rel="stylesheet" href="css/magnific-popup.css">
    <link rel="stylesheet" href="css/templatemo-dream-pulse.css" />
 
</head>
<body>

    <main class="container-fluid">
        <div class="row">
            <nav id="tmSidebar" class="tm-bg-black-transparent tm-sidebar">
                <button class="navbar-toggler" type="button" aria-label="Toggle navigation">
                    <i class="fas fa-bars"></i>
                </button>
                <div class="tm-sidebar-sticky">
                    <div class="tm-brand-box">
                        <div class="tm-double-border-1">
                            <div class="tm-double-border-2">
                                <h1 class="tm-brand text-uppercase">Employment Project</h1>
                            </div>
                        </div>
                    </div>

                    <ul id="tmMainNav" class="nav flex-column text-uppercase text-right tm-main-nav">
                        <li class="nav-item">
                            <a  asp-area="" asp-controller="Apply_Job_Detail" asp-action="Index"  class="nav-link active">
                                <span class="d-inline-block mr-3">Apply Job</span>
                                <span class="d-inline-block tm-white-rect"></span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Candidate_Detail" asp-action="Index" class="nav-link">
                                <span class="d-inline-block mr-3">Candidate</span>
                                <span class="d-inline-block tm-white-rect"></span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-area="" asp-controller="Employer_Detail" asp-action="Index" class="nav-link">
                                <span class="d-inline-block mr-3">Employer</span>
                                <span class="d-inline-block tm-white-rect"></span>
                            </a>
                        </li>

                        <li class="nav-item">
                            <a asp-area="" asp-controller="Job_Detail" asp-action="Index" class="nav-link">
                                <span class="d-inline-block mr-3">Job</span>
                                <span class="d-inline-block tm-white-rect"></span>
                            </a>
                        </li>
                        <li>
                            <partial name="_LoginPartial" />
                        </li>
                       
                    </ul>

                </div>
            </nav>

            <main role="main" class="ml-sm-auto col-12">
                <div class="parallax-window"
                     data-parallax="scroll"
                     data-image-src="img/h.jpeg">
                    <div class="tm-section-wrap">
                        <section id="intro" class="tm-section">
                            <div class="tm-bg-white-transparent tm-intro">
                                <h2 class="tm-section-title mb-5 text-uppercase tm-color-primary">Choose a job you "LOVE"</h2>
                                <p class="tm-color-gray">
                                  "IF you love your work, if you enjoy it, you are already a success"  
                                </p>
                                <p class="mb-0 tm-color-gray">
                                   
                                </p>
                            </div>
                        </section>
                    </div>
                </div>

                <div class="tm-section-wrap bg-white">
                    <section id="about" class="row tm-section">
                      

                                @RenderBody()
                            

                    </section>
                </div>

                <!--
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employement_Project_MVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Apply_Job_Detail" asp-action="Index">Apply Job </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Candidate_Detail" asp-action="Index">Candidate </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employer_Detail" asp-action="Index">Employer </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Job_Detail" asp-action="Index">Job </a>
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
        -->
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>

              

                <script src="js/jquery.min.js"></script>
                <script src="js/jquery.singlePageNav.min.js"></script>
                <script src="js/parallax.min.js"></script>
                <script src="slick/slick.min.js"></script>
                <script src="js/jquery.magnific-popup.min.js"></script>
                <!-- <script src="js/templatemo-scripts.js"></script>-->
                <!--
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
        -->
</body>
</html>